### Data Exploring

In [1]:
import pandas as pd

# load the dataset
df = pd.read_csv('cnn_news_articles_final.csv')

In [2]:
# print firt 5 rows
df.head()

,Index,Author,Date published,Category,Section,Url,Headline,Description,Keywords,Second headline,Article text,Unnamed: 0
0,0.0,"Jacopo Prisco, CNN",2021-07-15 02:46:59,news,world,https://www.cnn.com/2021/07/14/world/tusimple-...,"There's a shortage of truckers, but TuSimple t...",The e-commerce boom has exacerbated a global t...,"world, There's a shortage of truckers, but TuS...","There's a shortage of truckers, but TuSimple t...","(CNN)Right now, there's a shortage of truck d...",NaN
1,1.0,"Stephanie Bailey, CNN",2021-05-12 07:52:09,news,world,https://www.cnn.com/2021/05/12/world/ironhand-...,Bioservo's robotic 'Ironhand' could protect fa...,Working in a factory can mean doing the same t...,"world, Bioservo's robotic 'Ironhand' could pro...",A robotic 'Ironhand' could protect factory wor...,(CNN)Working in a factory or warehouse can me...,NaN
2,2.0,"Words by Stephanie Bailey, video by Zahra Jamshed",2021-06-16 02:51:30,news,asia,https://www.cnn.com/2021/06/15/asia/swarm-robo...,This swarm of robots gets smarter the more it ...,"In a Hong Kong warehouse, a swarm of autonomou...","asia, This swarm of robots gets smarter the mo...",This swarm of robots gets smarter the more it ...,"(CNN)In a Hong Kong warehouse, a swarm of aut...",NaN
3,3.0,Kathryn Vasel,2022-03-18 14:37:21,business,success,https://www.cnn.com/2022/03/18/success/pandemi...,"Two years later, remote work has changed milli...",Here's a look at how the pandemic reshaped peo...,"success, Two years later, remote work has chan...","Two years later, remote work has changed milli...",The pandemic thrust the working world into a n...,NaN
4,4.0,"Paul R. La Monica, CNN Business",2022-03-19 11:41:08,business,investing,https://www.cnn.com/2022/03/19/investing/march...,Why March is so volatile for stocks - CNN,March Madness isn't just for college basketbal...,"investing, Why March is so volatile for stocks...",Why March is so volatile for stocks,New York (CNN Business)March Madness isn't jus...,NaN

In [3]:
# print last 5 rows
df.tail()

,Index,Author,Date published,Category,Section,Url,Headline,Description,Keywords,Second headline,Article text,Unnamed: 0
41872,NaN,NaN,NaN,politics,NaN,https://edition.cnn.com/2023/01/01/politics/mc...,McCarthy commits to key concession in call wit...,House GOP leader Kevin McCarthy outlined some ...,"domestic alerts, domestic-us politics, governm...",NaN,House GOP leader Kevin McCarthy outlined some ...,3924.0
41873,NaN,NaN,NaN,politics,NaN,https://edition.cnn.com/2023/02/04/politics/ch...,What to know about the suspected Chinese spy b...,A suspected Chinese surveillance balloon in th...,"asia, brand safety-nsf sensitive, brand safety...",NaN,A suspected Chinese surveillance balloon in th...,3925.0
41874,NaN,NaN,NaN,politics,NaN,https://edition.cnn.com/2023/02/03/politics/us...,Why the US hasn't shot down the suspected Chin...,As the US and its Canadian partners continue t...,NaN,NaN,As the US and its Canadian partners continue t...,3926.0
41875,NaN,NaN,NaN,politics,NaN,https://edition.cnn.com/2023/01/25/politics/ch...,Chinese engineer sentenced to 8 years in US pr...,A former graduate student in Chicago was sente...,"armed forces, asia, brand safety-nsf crime, br...",NaN,A former graduate student in Chicago was sente...,3927.0
41876,NaN,NaN,NaN,world,NaN,https://edition.cnn.com/2023/02/15/europe/russ...,Tensions mount at the Belarus-Ukraine border a...,Tensions are mounting at the border between Uk...,"belarus, border control, brand safety-nsf sens...",NaN,Tensions are mounting at the border between Uk...,3928.0

In [5]:
# print the dimensions 
df.shape

(41877, 12)

In [8]:
# print information about each column (data type and non-null values)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41877 entries, 0 to 41876
Data columns (total 12 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Index            37949 non-null  float64
 1   Author           37949 non-null  object
 2   Date published   37949 non-null  object
 3   Category         41877 non-null  object
 4   Section          37949 non-null  object
 5   Url              41877 non-null  object
 6   Headline         41877 non-null  object
 7   Description      41873 non-null  object
 8   Keywords         40735 non-null  object
 9   Second headline  37949 non-null  object
 10  Article text     41868 non-null  object
 11  Unnamed: 0       3928 non-null   float64
dtypes: float64(2), object(10)
memory usage: 3.8+ MB

In [12]:
# print how many unique counts in each column
df.nunique()

Index              37949
Author             11744
Date published     37948
Category              14
Section               55
Url                41877
Headline           41785
Description        41751
Keywords           40623
Second headline    37881
Article text       41846
Unnamed: 0          3928
dtype: int64

In [10]:
# print each unique counts of Category column
df['Category'].value_counts()

Category
news             18077
sport            15789
politics          3026
business          1775
health            1037
world              820
entertainment      557
us                 317
opinions           280
weather            115
travel              52
style               16
cnn                 11
vr                   5
Name: count, dtype: int64

In [13]:
# print each unique counts of Section column
df['Section'].value_counts()

Section
europe                  10635
sport                    5639
football                 4911
politics                 2461
us                       2119
tennis                   2100
uk                       1856
golf                     1498
motorsport               1386
opinions                  850
world                     614
health                    557
australia                 547
entertainment             390
asia                      301
business                  284
americas                  217
tech                      205
opinion                   188
africa                    183
middleeast                148
weather                   131
china                     103
living                     93
media                      85
investing                  82
economy                    64
success                    41
perspectives               41
travel                     38
app-news-section           30
india                      28
justice                    25
energy                     21
showbiz                    21
homes                      15
cars                        7
vr                          5
business-food               4
worldsport                  4
skiing                      3
equestrian                  3
business-money              3
app-politics-section        2
horseracing                 1
app-tech-section            1
cnn10                       1
movies                      1
foodanddrink                1
fashion                     1
intl_business               1
intl_world                  1
celebrities                 1
business-india              1
sailing                     1
Name: count, dtype: int64

In [14]:
# check for any missing values 
df.isnull().sum()

Index               3928
Author              3928
Date published      3928
Category               0
Section             3928
Url                    0
Headline               0
Description            4
Keywords            1142
Second headline     3928
Article text           9
Unnamed: 0         37949
dtype: int64

In [16]:
# check for any duplication
print(df.duplicated().sum())

# filter the dataFrame for duplicate rows
duplicate_rows = df[df.duplicated(keep=False)]

# print the duplicate data
print(duplicate_rows)

0
Empty DataFrame
Columns: [Index, Author, Date published, Category, Section, Url, Headline, Description, Keywords, Second headline, Article text, Unnamed: 0]
Index: []